services:
  web:
    build:
      context: .
      args:
        - VERSION=local
    volumes:
      - ./config:/config
    ports:
      - "8012:8000"
    restart: unless-stopped

  gotify:
    image: gotify/server
    ports:
      - "8180:80"
    volumes:
      - ./data/gotify/data:/app/data
    restart: unless-stopped

  psql:
    image: postgres:15
    environment:
      POSTGRES_USER: abr
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audiobookrequest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

