"""add succ/failed event type

Revision ID: 76d7ccb8a116
Revises: 497b4366eb45
Create Date: 2025-03-08 21:48:18.673994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76d7ccb8a116"
down_revision: Union[str, None] = "497b4366eb45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE eventenum ADD VALUE 'on_successful_download'")
        op.execute("ALTER TYPE eventenum ADD VALUE 'on_failed_download'")
    enum_type = sa.Enum(
        "on_new_request",
        "on_successful_download",
        "on_failed_download",
        name="eventenum",
    )
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.alter_column(
            "event",
            existing_type=sa.VARCHAR(length=14),
            type_=enum_type,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TABLE notification ALTER COLUMN event TYPE VARCHAR")
    else:
        with op.batch_alter_table("notification", schema=None) as batch_op:
            batch_op.alter_column(
                "event",
                existing_type=sa.Enum(
                    "on_new_request",
                    "on_successful_download",
                    "on_failed_download",
                    name="eventenum",
                ),
                type_=sa.VARCHAR(length=14),
                existing_nullable=False,
            )

    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TYPE eventenum")
        op.execute("CREATE TYPE eventenum AS ENUM ('on_new_request')")
        op.execute(
            "ALTER TABLE notification ALTER COLUMN event TYPE eventenum USING event::eventenum"
        )

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.alter_column(
            "event",
            existing_type=sa.VARCHAR(length=14),
            type_=sa.Enum("on_new_request", name="eventenum"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
