"""migrate mam enabled

Revision ID: 9420621b2ed4
Revises: cd14e5f0977c
Create Date: 2025-08-28 10:22:51.110956

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9420621b2ed4"
down_revision: Union[str, None] = "cd14e5f0977c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE Config SET key='MyAnonamouse_enabled' where key='mam_active'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE Config SET key='mam_active' where key='MyAnonamouse_enabled'")
    # ### end Alembic commands ###
